# Generated by Django 2.2.16 on 2022-02-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['pub_date', '-id'], 'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
