# Generated by Django 2.2.16 on 2022-02-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['pub_date', 'id'], 'ordering': ['-pub_date']},
        ),
    ]
