# Generated by Django 2.2.16 on 2022-02-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220222_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['created', 'id'], 'ordering': ['-created']},
        ),
    ]
